{"message": "数据库初始化失败: (pymysql.err.OperationalError) (2003, \"Can't connect to MySQL server on 'localhost'\")\n(Background on this error at: https://sqlalche.me/e/20/e3q8)", "timestamp": "2025-09-25T12:46:55.112598", "level": "ERROR", "logger": "smartspider", "module": "main", "function": "startup_event", "line": 38, "thread": 3720, "thread_name": "MainThread", "process": 10164, "process_name": "MainProcess"}
{"message": "任务停止失败: db787928-92b2-4d9e-b2db-ccd78545a015", "timestamp": "2025-09-25T12:56:16.431917", "level": "ERROR", "logger": "smartspider", "module": "task_service", "function": "stop_task", "line": 104, "thread": 19372, "thread_name": "MainThread", "process": 8724, "process_name": "MainProcess"}
